import { useState } from "react";
import { useRoute, Link, useLocation } from "wouter";
import {
  useGetProject,
  getGetProjectQueryKey,
  useGetStory,
  getGetStoryQueryKey,
  useUpdateStory,
  useDeleteStory,
  useCreateTask,
  useUpdateTask,
  useListTasks,
  getListTasksQueryKey,
  useListMembers,
  getGetDashboardSummaryQueryKey,
  getListNotificationsQueryKey,
} from "@workspace/api-client-react";
import { Calendar } from "@/components/ui/calendar";
import { formatDistanceToNow } from 'date-fns';
import { useQueryClient } from "@tanstack/react-query";
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Edit,
  Trash2,
  Plus,
  Clock,
  AlertCircle,
  ChevronRight,
} from "lucide-react";

// Manual fetch for story since there's no useGetStory generated by default? 
// Wait, looking at api.ts, there might not be getStory, let's check. Actually, I can use custom fetch or we might have it.
// To be safe, I'll fetch project and find the story, OR write a custom query if getGetStoryQueryKey is not there.
// The prompt says: useGetStoryQueryKey(storyId). So there must be a useGetStory! Wait, let me check the api.ts snippet if it has useGetStory. 
// If not, I'll make a react-query wrapper.
// Actually, the prompt says "On any mutation, invalidate getGetStoryQueryKey(storyId)", so it probably exists. If not, I'll use customQuery.

const taskSchema = z.object({
  title: z.string().min(1, "Title is required"),
  description: z.string().optional(),
  status: z.enum(["todo", "in_progress", "blocked", "done"]),
  assigneeId: z.union([
    z.coerce.number().optional(),
    z.literal(""),
    z.literal("unassigned"),
  ]),
  estimateHours: z.coerce.number().min(0).optional().or(z.literal("")),
  dueDate: z.string().optional()
});

const storyUpdateSchema = z.object({
  title: z.string().min(1, "Title is required"),
  description: z.string().optional(),
  acceptanceCriteria: z.string().optional(),
  priority: z.enum(["low", "medium", "high", "urgent"]),
  status: z.enum(["backlog", "ready", "in_progress", "review", "done"]),
  storyPoints: z.coerce.number().min(0).optional().or(z.literal("")),
});

export function StoryDetail() {
  const [, params] = useRoute("/stories/:storyId");
  const storyId = Number(params?.storyId);
  const [, setLocation] = useLocation();
  const queryClient = useQueryClient();

  const [isTaskDialogOpen, setIsTaskDialogOpen] = useState(false);
  const [isEditStoryDialogOpen, setIsEditDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<any>(null);

  const { data: story, isLoading: isStoryLoading } = useGetStory(storyId, {
    query: { enabled: !!storyId, queryKey: getGetStoryQueryKey(storyId) },
  });

  const { data: project } = useGetProject(story?.projectId || 0, {
    query: { enabled: !!story?.projectId, queryKey: getGetProjectQueryKey(story?.projectId || 0) }
  });

  const { data: tasks = [] } = useListTasks(storyId, {
    query: { enabled: !!storyId, queryKey: getListTasksQueryKey(storyId) }
  });

  const { data: members = [] } = useListMembers();

  const updateStory = useUpdateStory();
  const deleteStory = useDeleteStory();
  const createTask = useCreateTask();
  const updateTask = useUpdateTask();

  const taskForm = useForm<z.infer<typeof taskSchema>>({
    resolver: zodResolver(taskSchema),
    defaultValues: { title: "", description: "", status: "todo", assigneeId: "", estimateHours: "", dueDate: "" }
  });

  const storyForm = useForm<z.infer<typeof storyUpdateSchema>>({
    resolver: zodResolver(storyUpdateSchema),
    defaultValues: { title: "", description: "", acceptanceCriteria: "", priority: "medium", status: "backlog", storyPoints: "" }
  });

  if (story && storyForm.getValues("title") === "" && !isEditStoryDialogOpen) {
    storyForm.reset({
      title: story.title,
      description: story.description || "",
      acceptanceCriteria: story.acceptanceCriteria || "",
      priority: story.priority as any,
      status: story.status as any,
      storyPoints: story.storyPoints?.toString() || ""
    });
  }

  function onStorySubmit(values: z.infer<typeof storyUpdateSchema>) {
    updateStory.mutate({ 
      storyId, 
      data: {
        ...values,
        storyPoints: values.storyPoints === "" ? null : Number(values.storyPoints)
      } 
    }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getGetStoryQueryKey(storyId) });
        if (story) queryClient.invalidateQueries({ queryKey: getGetProjectQueryKey(story.projectId) });
        queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() });
        toast.success("Story updated successfully");
        setIsEditDialogOpen(false);
      },
      onError: (error) => toast.error(error.error || "Failed to update story")
    });
  }

  function handleDeleteStory() {
    if (!story) return;
    deleteStory.mutate({ storyId }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getGetProjectQueryKey(story.projectId) });
        queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() });
        toast.success("Story deleted");
        setLocation(`/projects/${story.projectId}`);
      },
      onError: (error) => toast.error(error.error || "Failed to delete story")
    });
  }

  function onTaskSubmit(values: z.infer<typeof taskSchema>) {
    const payload = {
      ...values,
      assigneeId:
        values.assigneeId === "" || values.assigneeId === "unassigned"
          ? null
          : Number(values.assigneeId),
      estimateHours: values.estimateHours === "" ? null : Number(values.estimateHours),
      dueDate: values.dueDate || null
    };

    if (editingTask) {
      updateTask.mutate({ taskId: editingTask.id, data: payload }, {
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: getListTasksQueryKey(storyId) });
          queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() });
          queryClient.invalidateQueries({ queryKey: getListNotificationsQueryKey() });
          toast.success("Task updated");
          setIsTaskDialogOpen(false);
          setEditingTask(null);
        },
        onError: (error) => toast.error(error.error || "Failed to update task")
      });
    } else {
      createTask.mutate({ storyId, data: payload }, {
        onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: getListTasksQueryKey(storyId) });
          queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() });
          queryClient.invalidateQueries({ queryKey: getListNotificationsQueryKey() });
          toast.success("Task created");
          setIsTaskDialogOpen(false);
          taskForm.reset();
        },
        onError: (error) => toast.error(error.error || "Failed to create task")
      });
    }
  }

  function handleTaskStatusChange(taskId: number, newStatus: any) {
    updateTask.mutate({ taskId, data: { status: newStatus } }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListTasksQueryKey(storyId) });
        queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() });
        queryClient.invalidateQueries({ queryKey: getListNotificationsQueryKey() });
        toast.success("Task status updated");
      }
    });
  }

  function handleStoryStatusChange(newStatus: any) {
    updateStory.mutate({ storyId, data: { status: newStatus } }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getGetStoryQueryKey(storyId) });
        if (story) queryClient.invalidateQueries({ queryKey: getGetProjectQueryKey(story.projectId) });
        queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() });
        queryClient.invalidateQueries({ queryKey: getListNotificationsQueryKey() });
        toast.success("Story status updated");
      }
    });
  }

  function openNewTask() {
    setEditingTask(null);
    taskForm.reset({ title: "", description: "", status: "todo", assigneeId: "", estimateHours: "", dueDate: "" });
    setIsTaskDialogOpen(true);
  }

  function openEditTask(task: any) {
    setEditingTask(task);
    taskForm.reset({
      title: task.title,
      description: task.description || "",
      status: task.status,
      assigneeId: task.assigneeId?.toString() || "",
      estimateHours: task.estimateHours?.toString() || "",
      dueDate: task.dueDate ? task.dueDate.split('T')[0] : ""
    });
    setIsTaskDialogOpen(true);
  }

  if (isStoryLoading) {
    return <div className="flex items-center justify-center h-64 text-muted-foreground">Loading story...</div>;
  }

  if (!story) {
    return (
      <div className="flex flex-col items-center justify-center h-64">
        <AlertCircle className="h-10 w-10 text-destructive mb-4" />
        <h2 className="text-xl font-semibold mb-2">Story Not Found</h2>
        <Button onClick={() => setLocation("/projects")} variant="outline">Back to Projects</Button>
      </div>
    );
  }

  const priorityColors = {
    low: "bg-muted text-muted-foreground",
    medium: "bg-secondary text-secondary-foreground",
    high: "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200",
    urgent: "bg-destructive text-destructive-foreground",
  };

  const tasksByStatus = {
    todo: tasks.filter(t => t.status === 'todo'),
    in_progress: tasks.filter(t => t.status === 'in_progress'),
    blocked: tasks.filter(t => t.status === 'blocked'),
    done: tasks.filter(t => t.status === 'done'),
  };

  return (
    <div className="space-y-6">
      {/* Breadcrumb & Header */}
      <div>
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-4">
          <Link href="/projects" className="hover:text-foreground">Projects</Link>
          <ChevronRight className="h-4 w-4" />
          {project ? (
            <>
              <Link href={`/projects/${project.id}`} className="hover:text-foreground">{project.name}</Link>
              <ChevronRight className="h-4 w-4" />
            </>
          ) : null}
          <span className="text-foreground">{story.title}</span>
        </div>

        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 bg-card border rounded-lg p-6">
          <div className="space-y-4 flex-1">
            <div>
              <h1 className="text-2xl font-bold tracking-tight mb-2">{story.title}</h1>
              <div className="flex flex-wrap items-center gap-3">
                <Select value={story.status} onValueChange={handleStoryStatusChange}>
                  <SelectTrigger className="w-[140px] h-8 bg-secondary border-none">
                    <SelectValue placeholder="Status" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="backlog">Backlog</SelectItem>
                    <SelectItem value="ready">Ready</SelectItem>
                    <SelectItem value="in_progress">In Progress</SelectItem>
                    <SelectItem value="review">Review</SelectItem>
                    <SelectItem value="done">Done</SelectItem>
                  </SelectContent>
                </Select>
                <Badge className={priorityColors[story.priority as keyof typeof priorityColors]} variant="secondary">
                  {story.priority} Priority
                </Badge>
                {story.storyPoints && (
                  <Badge variant="outline">{story.storyPoints} Points</Badge>
                )}
              </div>
            </div>
            
            {(story.description || story.acceptanceCriteria) && (
              <div className="grid sm:grid-cols-2 gap-6 pt-4 border-t">
                {story.description && (
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">Description</h3>
                    <p className="text-sm whitespace-pre-wrap">{story.description}</p>
                  </div>
                )}
                {story.acceptanceCriteria && (
                  <div>
                    <h3 className="text-sm font-medium text-muted-foreground mb-1">Acceptance Criteria</h3>
                    <p className="text-sm whitespace-pre-wrap">{story.acceptanceCriteria}</p>
                  </div>
                )}
              </div>
            )}
          </div>
          
          <div className="flex gap-2 shrink-0">
            <Dialog open={isEditStoryDialogOpen} onOpenChange={setIsEditDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" size="sm"><Edit className="mr-2 h-4 w-4" /> Edit</Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Edit Story</DialogTitle>
                </DialogHeader>
                <Form {...storyForm}>
                  <form onSubmit={storyForm.handleSubmit(onStorySubmit)} className="space-y-4">
                    <FormField control={storyForm.control} name="title" render={({ field }) => (
                      <FormItem><FormLabel>Story Title</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <div className="grid grid-cols-2 gap-4">
                      <FormField control={storyForm.control} name="priority" render={({ field }) => (
                        <FormItem><FormLabel>Priority</FormLabel>
                          <Select onValueChange={field.onChange} defaultValue={field.value}>
                            <FormControl><SelectTrigger><SelectValue placeholder="Priority" /></SelectTrigger></FormControl>
                            <SelectContent>
                              <SelectItem value="low">Low</SelectItem>
                              <SelectItem value="medium">Medium</SelectItem>
                              <SelectItem value="high">High</SelectItem>
                              <SelectItem value="urgent">Urgent</SelectItem>
                            </SelectContent>
                          </Select>
                        <FormMessage /></FormItem>
                      )} />
                      <FormField control={storyForm.control} name="storyPoints" render={({ field }) => (
                        <FormItem><FormLabel>Story Points</FormLabel><FormControl><Input type="number" min="0" placeholder="e.g. 3" {...field} /></FormControl><FormMessage /></FormItem>
                      )} />
                    </div>
                    <FormField control={storyForm.control} name="description" render={({ field }) => (
                      <FormItem><FormLabel>Description</FormLabel><FormControl><Textarea {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={storyForm.control} name="acceptanceCriteria" render={({ field }) => (
                      <FormItem><FormLabel>Acceptance Criteria</FormLabel><FormControl><Textarea {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <Button type="submit" className="w-full" disabled={updateStory.isPending}>Save Changes</Button>
                  </form>
                </Form>
              </DialogContent>
            </Dialog>

            <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="destructive" size="sm"><Trash2 className="mr-2 h-4 w-4" /> Delete</Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Are you sure?</DialogTitle>
                  <DialogDescription>
                    This will permanently delete the story and all its tasks.
                  </DialogDescription>
                </DialogHeader>
                <DialogFooter className="mt-4">
                  <Button variant="outline" onClick={() => setIsDeleteDialogOpen(false)}>Cancel</Button>
                  <Button variant="destructive" onClick={handleDeleteStory} disabled={deleteStory.isPending}>Delete</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </div>

      {/* Tasks Kanban Board */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-bold tracking-tight">Tasks</h2>
          <Dialog open={isTaskDialogOpen} onOpenChange={setIsTaskDialogOpen}>
            <Button onClick={openNewTask}><Plus className="mr-2 h-4 w-4" /> New Task</Button>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>{editingTask ? "Edit Task" : "Create New Task"}</DialogTitle>
              </DialogHeader>
              <Form {...taskForm}>
                <form onSubmit={taskForm.handleSubmit(onTaskSubmit)} className="space-y-4">
                  <FormField control={taskForm.control} name="title" render={({ field }) => (
                    <FormItem><FormLabel>Title</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <div className="grid grid-cols-2 gap-4">
                    <FormField control={taskForm.control} name="status" render={({ field }) => (
                      <FormItem><FormLabel>Status</FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl><SelectTrigger><SelectValue placeholder="Status" /></SelectTrigger></FormControl>
                          <SelectContent>
                            <SelectItem value="todo">To Do</SelectItem>
                            <SelectItem value="in_progress">In Progress</SelectItem>
                            <SelectItem value="blocked">Blocked</SelectItem>
                            <SelectItem value="done">Done</SelectItem>
                          </SelectContent>
                        </Select>
                      <FormMessage /></FormItem>
                    )} />
                    <FormField control={taskForm.control} name="assigneeId" render={({ field }) => (
                      <FormItem><FormLabel>Assignee</FormLabel>
                        <Select onValueChange={field.onChange} value={field.value?.toString() || ""}>
                          <FormControl><SelectTrigger><SelectValue placeholder="Unassigned" /></SelectTrigger></FormControl>
                          <SelectContent>
                            <SelectItem value="unassigned">Unassigned</SelectItem>
                            {members.map(m => (
                              <SelectItem key={m.id} value={m.id.toString()}>{m.name}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      <FormMessage /></FormItem>
                    )} />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <FormField control={taskForm.control} name="estimateHours" render={({ field }) => (
                      <FormItem><FormLabel>Estimate (Hours)</FormLabel><FormControl><Input type="number" min="0" step="0.5" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={taskForm.control} name="dueDate" render={({ field }) => (
                      <FormItem><FormLabel>Due Date</FormLabel><FormControl><Input type="date" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                  </div>
                  <FormField control={taskForm.control} name="description" render={({ field }) => (
                    <FormItem><FormLabel>Description</FormLabel><FormControl><Textarea {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <Button type="submit" className="w-full" disabled={createTask.isPending || updateTask.isPending}>
                    {editingTask ? "Save Changes" : "Create Task"}
                  </Button>
                </form>
              </Form>
            </DialogContent>
          </Dialog>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-start">
          {Object.entries(tasksByStatus).map(([status, statusTasks]) => (
            <div key={status} className="bg-muted/50 rounded-lg p-3 min-h-[300px]">
              <div className="flex items-center justify-between mb-3 px-1">
                <h3 className="font-semibold text-sm capitalize">{status.replace('_', ' ')}</h3>
                <Badge variant="secondary" className="text-xs">{statusTasks.length}</Badge>
              </div>
              <div className="space-y-3">
                {statusTasks.map(task => (
                  <Card key={task.id} className="cursor-pointer hover:border-primary transition-colors shadow-sm group" onClick={() => openEditTask(task)}>
                    <CardContent className="p-3">
                      <div className="flex items-start justify-between gap-2 mb-2">
                        <span className="font-medium text-sm leading-tight group-hover:text-primary transition-colors">{task.title}</span>
                      </div>
                      
                      <div className="flex flex-col gap-2 mt-3">
                        <div className="flex items-center justify-between" onClick={e => e.stopPropagation()}>
                          <Select value={task.status} onValueChange={(val) => handleTaskStatusChange(task.id, val)}>
                            <SelectTrigger className="h-7 text-xs w-[110px]">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="todo">To Do</SelectItem>
                              <SelectItem value="in_progress">In Progress</SelectItem>
                              <SelectItem value="blocked">Blocked</SelectItem>
                              <SelectItem value="done">Done</SelectItem>
                            </SelectContent>
                          </Select>
                          
                          {task.estimateHours && (
                            <Badge variant="outline" className="text-[10px] h-5"><Clock className="w-3 h-3 mr-1" /> {task.estimateHours}h</Badge>
                          )}
                        </div>

                        <div className="flex items-center justify-between mt-1 pt-2 border-t text-xs text-muted-foreground">
                          <div className="flex items-center gap-1.5" title={task.assignee?.name || "Unassigned"}>
                            <Avatar className="w-5 h-5">
                              <AvatarFallback className="text-[10px] bg-primary/10 text-primary">
                                {task.assignee ? task.assignee.name.substring(0, 2).toUpperCase() : <User className="w-3 h-3" />}
                              </AvatarFallback>
                            </Avatar>
                            <span className="truncate max-w-[80px]">{task.assignee?.name || "Unassigned"}</span>
                          </div>
                          
                          {task.dueDate && (
                            <div className="flex items-center gap-1" title={new Date(task.dueDate).toLocaleDateString()}>
                              <Calendar className="w-3 h-3" />
                              {formatDistanceToNow(new Date(task.dueDate), { addSuffix: true })}
                            </div>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
                {statusTasks.length === 0 && (
                  <div className="text-center py-6 text-sm text-muted-foreground border-2 border-dashed border-border/50 rounded-lg">
                    No tasks
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

